/usr/lib/jvm/java-16-oracle/bin/java -classpath :/home/roshan/workspace/ekbana/bigdata/apostle/apostle-core/target/apostle-core-1.0-SNAPSHOT.jar\
:/home/roshan/.m2/repository/org/reflections/reflections/0.10.2/reflections-0.10.2.jar\
:/home/roshan/.m2/repository/org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.jar\
:/home/roshan/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar\
:/home/roshan/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar\
:/home/roshan/.m2/repository/org/springframework/spring-webflux/5.3.17/spring-webflux-5.3.17.jar\
:/home/roshan/.m2/repository/org/springframework/spring-beans/5.3.17/spring-beans-5.3.17.jar\
:/home/roshan/.m2/repository/org/springframework/spring-core/5.3.17/spring-core-5.3.17.jar\
:/home/roshan/.m2/repository/org/springframework/spring-jcl/5.3.17/spring-jcl-5.3.17.jar\
:/home/roshan/.m2/repository/org/springframework/spring-web/5.3.17/spring-web-5.3.17.jar\
:/home/roshan/.m2/repository/io/projectreactor/reactor-core/3.4.16/reactor-core-3.4.16.jar\
:/home/roshan/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar\
:/home/roshan/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.6.5/spring-boot-starter-web-2.6.5.jar\
:/home/roshan/.m2/repository/org/springframework/boot/spring-boot-starter/2.6.5/spring-boot-starter-2.6.5.jar\
:/home/roshan/.m2/repository/org/springframework/boot/spring-boot/2.6.5/spring-boot-2.6.5.jar\
:/home/roshan/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.6.5/spring-boot-autoconfigure-2.6.5.jar\
:/home/roshan/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.6.5/spring-boot-starter-logging-2.6.5.jar\
:/home/roshan/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar\
:/home/roshan/.m2/repository/ch/qos/logback/logback-core/1.2.11/logback-core-1.2.11.jar\
:/home/roshan/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.17.2/log4j-to-slf4j-2.17.2.jar\
:/home/roshan/.m2/repository/org/apache/logging/log4j/log4j-api/2.17.2/log4j-api-2.17.2.jar\
:/home/roshan/.m2/repository/org/slf4j/jul-to-slf4j/1.7.36/jul-to-slf4j-1.7.36.jar\
:/home/roshan/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar\
:/home/roshan/.m2/repository/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar\
:/home/roshan/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.6.5/spring-boot-starter-json-2.6.5.jar\
:/home/roshan/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.13.2/jackson-databind-2.13.2.jar\
:/home/roshan/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.13.2/jackson-annotations-2.13.2.jar\
:/home/roshan/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.13.2/jackson-core-2.13.2.jar\
:/home/roshan/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.13.2/jackson-datatype-jdk8-2.13.2.jar\
:/home/roshan/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.2/jackson-datatype-jsr310-2.13.2.jar\
:/home/roshan/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.13.2/jackson-module-parameter-names-2.13.2.jar\
:/home/roshan/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.6.5/spring-boot-starter-tomcat-2.6.5.jar\
:/home/roshan/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.60/tomcat-embed-core-9.0.60.jar\
:/home/roshan/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.60/tomcat-embed-el-9.0.60.jar\
:/home/roshan/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.60/tomcat-embed-websocket-9.0.60.jar\
:/home/roshan/.m2/repository/org/springframework/spring-webmvc/5.3.17/spring-webmvc-5.3.17.jar\
:/home/roshan/.m2/repository/org/springframework/spring-aop/5.3.17/spring-aop-5.3.17.jar\
:/home/roshan/.m2/repository/org/springframework/spring-context/5.3.17/spring-context-5.3.17.jar\
:/home/roshan/.m2/repository/org/springframework/spring-expression/5.3.17/spring-expression-5.3.17.jar com.ekbana.bigdata.ApostleApp --spring.config.location=file:/home/roshan/workspace/ekbana/bigdata/apostle/application.properties
